language: rust
rust:
  - stable
  - beta
  - nightly

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH

after_success:
  # Upload docs to github pages
  - travis-cargo --only stable doc-upload
  # Upload to Codecov
  - travis-cargo coveralls --no-sudo --verify 
    && bash <(curl -s https://codecov.io/bash)

